version: '3'

services:
  web:
    container_name: yearbook_web
    build: .
    command: npm start
    env_file:
      - yearbook.env 
    ports:
      - "8000:8000"
    volumes:
      - .:/home/app/web
      - node_modules:/home/app/web/node_modules

  nginx:
    container_name: yearbook_nginx
    image: nginx:mainline-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports: 
      - "1337:80"
    depends_on:
      - web

volumes:
  mongo_data:
  node_modules:
